DELETE FROM ST_TSTANDORT;


INSERT INTO ST_TSTANDORT (NAME, NUMMER) VALUES ('Stuttgart', 'S');
INSERT INTO ST_TSTANDORT (NAME, NUMMER) VALUES ('München', 'M');
INSERT INTO ST_TSTANDORT (NAME, NUMMER) VALUES ('Mannheim', 'MA');


DELETE FROM ST_TABTEILUNG;

INSERT INTO ST_TABTEILUNG (FK_STANDORT, FK_PARENT, NAME, ABT_NUMMER) VALUES (  1, NULL, 'Real Estate', '_RE');
INSERT INTO ST_TABTEILUNG (FK_STANDORT, FK_PARENT, NAME, ABT_NUMMER) VALUES (  1, NULL, 'Sales', '_SA');
INSERT INTO ST_TABTEILUNG (FK_STANDORT, FK_PARENT, NAME, ABT_NUMMER) VALUES (  1, NULL, 'Production A', '_PA');
INSERT INTO ST_TABTEILUNG (FK_STANDORT, FK_PARENT, NAME, ABT_NUMMER) VALUES (  2, NULL, 'Production B1', '_PB1');
INSERT INTO ST_TABTEILUNG (FK_STANDORT, FK_PARENT, NAME, ABT_NUMMER) VALUES (  2, NULL, 'Production B2', '_PB2');
INSERT INTO ST_TABTEILUNG (FK_STANDORT, FK_PARENT, NAME, ABT_NUMMER) VALUES (  3, NULL, 'IT', '_IT');
INSERT INTO ST_TABTEILUNG (FK_STANDORT, FK_PARENT, NAME, ABT_NUMMER) VALUES (  3, NULL, 'R/D', '_RD');
INSERT INTO ST_TABTEILUNG (FK_STANDORT, FK_PARENT, NAME, ABT_NUMMER) VALUES (  3, NULL, 'LEGAL', '_LG');

INSERT INTO ST_TABTEILUNG (FK_STANDORT, FK_PARENT, ABT_NUMMER, NAME) SELECT  3, ID, 'M/A', '_MA' FROM ST_TABTEILUNG WHERE ABT_NUMMER = '_LG';
INSERT INTO ST_TABTEILUNG (FK_STANDORT, FK_PARENT, ABT_NUMMER, NAME) SELECT   3, ID, 'LEGAL GENERAL', '_LG' FROM ST_TABTEILUNG WHERE ABT_NUMMER = '_LG';

-- SELECT * from ST_TABTEILUNG


DELETE FROM ST_TMATGRUPPE;

INSERT INTO ST_TMATGRUPPE (FK_PARENT, MATCODE, NAME) VALUES (NULL, '0001', 'C-Artikel');
INSERT INTO ST_TMATGRUPPE (FK_PARENT, MATCODE, NAME) VALUES (NULL, '0002', 'Dienstleistungen');
INSERT INTO ST_TMATGRUPPE (FK_PARENT, MATCODE, NAME) VALUES (NULL, '0003', 'IT-Dienstleistungen');
INSERT INTO ST_TMATGRUPPE (FK_PARENT, MATCODE, NAME) VALUES (NULL, '0004', 'Bleche');
INSERT INTO ST_TMATGRUPPE (FK_PARENT, MATCODE, NAME) VALUES (NULL, '0005', 'Kabel');
INSERT INTO ST_TMATGRUPPE (FK_PARENT, MATCODE, NAME) VALUES (NULL, '0006', 'Bürobedarf');
INSERT INTO ST_TMATGRUPPE (FK_PARENT, MATCODE, NAME) VALUES (NULL, '0007', 'Schmierstoffe/Öle');
INSERT INTO ST_TMATGRUPPE (FK_PARENT, MATCODE, NAME) VALUES (NULL, '0008', 'Lösungsmittel');
INSERT INTO ST_TMATGRUPPE (FK_PARENT, MATCODE, NAME) VALUES (NULL, '0009', 'Logistik');
INSERT INTO ST_TMATGRUPPE (FK_PARENT, MATCODE, NAME) VALUES (NULL, '0010', 'Reinigung');


DELETE FROM ST_TSUPPLIER;

INSERT INTO ST_TSUPPLIER (FIRMA, KRED_ID) VALUES ('Schüttelknecht GmbH'    ,   '94658939' );
INSERT INTO ST_TSUPPLIER (FIRMA, KRED_ID) VALUES ('Universal Stuffing Inc.',   '94657865' );
INSERT INTO ST_TSUPPLIER (FIRMA, KRED_ID) VALUES ('Scheibenkleister AG.'   ,   '94659033' );
INSERT INTO ST_TSUPPLIER (FIRMA, KRED_ID) VALUES ('Bertil Fichtl GmbH' || chr(38) || 'Co. KG', '94659278' );
INSERT INTO ST_TSUPPLIER (FIRMA, KRED_ID) VALUES ('Claudio Heysterkamp KG',    '94651245' );

DELETE FROM ST_RUMSATZTYP;

INSERT INTO ST_RUMSATZTYP (UMSATZ_TYP) VALUES ('SAP FI/CO');
INSERT INTO ST_RUMSATZTYP (UMSATZ_TYP) VALUES ('SAP MM');



